In [1]:
import pandas as pd
import numpy as np

In [2]:
# term2 = [
#     "person", "kid", "cat", "bear", "dog", "sheep", "jellyfish", \
#     "cup of boba", "bowl of ramen", "apple", "pear", "burger", "fries", \
#     "sun", "moon", "star", "light bulb", "leaf",\
# ]
term2 = [
    "person", "kid", "cat", "bear", "dog", "sheep", "jellyfish", \
    "cup of boba", "apple", "burger", \
    "sun", "moon", "star"\
]
", ".join(term2)

'person, kid, cat, bear, dog, sheep, jellyfish, cup of boba, apple, burger, sun, moon, star'

In [3]:
term1 = [
    "happy", "sad", "surprised", "sleepy", "lovestruck", "evil"
]
", ".join(term1)

'happy, sad, surprised, sleepy, lovestruck, evil'

In [4]:
terms = []
for t1 in term1:
    for t2 in term2:
#         if t2 == "cup of boba":
#             terms.append("cup of {} boba".format(t1))
#         elif t2 == "bowl of ramen":
#             terms += ["bowl of {} ramen".format(t1)]
#         else:
        terms.append(" ".join([t1,t2]))

In [5]:
len(terms)

78

In [6]:
perms = np.random.permutation(np.arange(len(terms)))
perms

array([66, 75, 28, 63, 47, 33, 51,  0, 16, 23, 10, 72,  9, 71, 41, 69, 67,
        6, 24, 43, 29, 68, 22, 30, 52, 55, 73, 48, 21, 37, 40, 64, 76, 74,
        8, 35, 58, 18, 70, 54,  7, 61, 27, 38, 53, 45, 11, 77, 13, 14,  4,
       59, 44, 19,  1, 26, 17, 15, 57, 34, 65,  3, 36,  5, 39, 56, 46, 62,
       42, 60, 32,  2, 20, 12, 50, 25, 31, 49])

In [22]:
# 2 columns

g1_idx = list(perms)
g1_terms = np.array(terms)[g1_idx]
g3_terms = np.flip(g1_terms)

print(np.where(g1_terms == g3_terms))

data = {
    "PROMPT01" : list(g1_terms),
    "PROMPT02" : list(g3_terms),
}

df = pd.DataFrame.from_dict(data)
df.to_csv('/raid/xiaoyuz1/amazon_turk/2021_pilot/round1.csv', index=False)  
df


(array([], dtype=int64),)


PROMPT01                PROMPT02
0         lovestruck sheep          lovestruck sun
1               evil sheep  lovestruck cup of boba
2            surprised kid           sleepy burger
3        lovestruck person                evil dog
4           surprised star     surprised jellyfish
..                     ...                     ...
73     surprised jellyfish          surprised star
74                evil dog       lovestruck person
75           sleepy burger           surprised kid
76  lovestruck cup of boba              evil sheep
77          lovestruck sun        lovestruck sheep

[78 rows x 2 columns]

In [19]:
g1_terms[19]

'lovestruck kid'

In [20]:
g3_terms[19]

'happy dog'

In [7]:
# g1 = np.random.binomial(1, 0.5, len(terms))
# g2 = 1 - g1
# g1 = g1.astype(bool)
# g2 = g2.astype(bool)
g1_idx = list(perms[:int(len(terms)/2)])
g2_idx = list(perms[int(len(terms)/2):])

In [8]:
len(g1_idx), len(g2_idx)

(39, 39)

In [9]:
g1_terms = np.array(terms)[g1_idx]
np.random.shuffle(g1_terms)
g2_terms = np.array(terms)[g2_idx]
np.random.shuffle(g2_terms)

g3_terms = np.flip(g1_terms)
g4_terms = np.flip(g2_terms)

In [10]:
print(np.where(g1_terms == g2_terms))
print(np.where(g1_terms == g3_terms))
print(np.where(g1_terms == g4_terms))

print(np.where(g2_terms == g3_terms))
print(np.where(g2_terms == g4_terms))

print(np.where(g3_terms == g4_terms))

(array([], dtype=int64),)
(array([19]),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([19]),)
(array([], dtype=int64),)


In [30]:
data = {
    "PROMPT01" : list(g1_terms),
    "PROMPT02" : list(g2_terms),
    "PROMPT03" : list(g3_terms),
    "PROMPT04" : list(g4_terms),
}

In [31]:
df = pd.DataFrame.from_dict(data)
df

PROMPT01                PROMPT02  \
0                 happy leaf           surprised sun   
1      lovestruck light bulb                sad pear   
2                  sad fries         evil light bulb   
3           lovestruck sheep   surprised cup of boba   
4           evil cup of boba    surprised light bulb   
5        happy bowl of ramen            sleepy apple   
6             surprised moon         lovestruck moon   
7                 sleepy dog                sad moon   
8                 happy bear               happy cat   
9          sad bowl of ramen              happy moon   
10                  sad leaf           surprised dog   
11         lovestruck burger     surprised jellyfish   
12          sleepy jellyfish                 sad dog   
13                happy pear               happy dog   
14                 evil bear  lovestruck cup of boba   
15           surprised apple               evil moon   
16                  evil cat              happy star   
17           surprised fries       sleepy light bulb   
18            evil jellyfish              sad burger   
19                  evil sun               happy kid   
20            lovestruck sun      evil bowl of ramen   
21              sleepy fries       happy cup of boba   
22               sleepy moon                 sad sun   
23               evil burger         happy jellyfish   
24           sad cup of boba         surprised sheep   
25               happy sheep              evil fries   
26          lovestruck fries              sleepy kid   
27              happy burger              evil sheep   
28                sleepy sun      sleepy cup of boba   
29             sleepy burger         lovestruck leaf   
30               sleepy pear          surprised bear   
31               happy fries            happy person   
32               sleepy leaf          surprised pear   
33            surprised star         lovestruck pear   
34  lovestruck bowl of ramen    sleepy bowl of ramen   
35            surprised leaf           sad jellyfish   
36                 evil leaf          sad light bulb   
37             sleepy person                sad star   
38                  evil kid               sad sheep   
39            lovestruck kid        surprised burger   
40                 evil star        happy light bulb   
41             surprised cat                sad bear   
42          lovestruck apple                 sad cat   
43          surprised person                 sad kid   
44            lovestruck dog              sleepy cat   
45           lovestruck bear       lovestruck person   
46                 sad apple              sad person   
47               sleepy bear          lovestruck cat   
48   surprised bowl of ramen         lovestruck star   
49                 happy sun             evil person   
50      lovestruck jellyfish             sleepy star   
51                 evil pear             happy apple   
52             surprised kid            sleepy sheep   
53                  evil dog              evil apple   

                    PROMPT03                PROMPT04  
0                   evil dog              evil apple  
1              surprised kid            sleepy sheep  
2                  evil pear             happy apple  
3       lovestruck jellyfish             sleepy star  
4                  happy sun             evil person  
5    surprised bowl of ramen         lovestruck star  
6                sleepy bear          lovestruck cat  
7                  sad apple              sad person  
8            lovestruck bear       lovestruck person  
9             lovestruck dog              sleepy cat  
10          surprised person                 sad kid  
11          lovestruck apple                 sad cat  
12             surprised cat                sad bear  
13                 evil star        happy light bulb  
14            lovestruck kid        surprised burger  
15                  evil kid               sad sheep  
16  

In [32]:
df.to_csv('/raid/xiaoyuz1/amazon_turk/2021_pilot/round1.csv', index=False)  

In [33]:
2.5 * 53

132.5